baseURL = "https://chi-chi-sticks.netlify.com/"
languageCode = "th-th"
title = "(: เซียมซีเสี่ยงทาย :)"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "ChiChi"
    description = "เซียมซี คือ เครื่องทำนายโชคชะตาตามศาลเจ้าหรือวัด ลักษณะเป็นติ้วไม้ไผ่ มีหมายเลขกำกับใส่ในกระบอก ผู้เสี่ยงทายต้องเขย่าให้ร่วงจากกระบอกได้หมายเลขใดก็ไปดูคำทำนายใบเซียมซีหมายเลขนั้น."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/chi-chi-results/"
    name = "Chi-Chi Sticks"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "chi.chi.sticks@gmail.com"
    name = "envelope-o"
    weight = 1
