# Site settings
baseurl = "https://chi-chi-sticks.netlify.com/"
languageCode = "th-th"
title = "เซียมซีเสี่ยงทาย"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-118785315-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "ไม้เซียมซีเสี่ยงทาย"
    subtitle = "เครื่องทำนายโชคชะตาตามศาลเจ้าหรือวัด ลักษณะเป็นติ้วไม้ไผ่ มีหมายเลขกำกับใส่ในกระบอก ผู้เสี่ยงทายต้องเขย่าให้ร่วงจากกระบอกได้หมายเลขใดก็ไปดูคำทำนายใบเซียมซีหมายเลขนั้น"
    author = "Theeraphol Wattanavekin"
    description = "Chi-Chi Sticks"
    keywords = "Chi-Chi, horoscope, destiny, luck, charm, future, prediction"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "ดูเพิ่มเติม"

    # Footer text
    footertext = "สงวนลิขสิทธิ์ โดย Chi-Chi Sticks Thailand"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
